version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wallet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wallet-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_backend
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - wallet-network
    mem_limit: 2g 
    mem_reservation: 1g
    expose:
      - "3000" 

  adminer:
    image: adminer
    container_name: wallet_adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - wallet-network

  test:
    build:
      context: .
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_PORT: '3306'
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
    depends_on:
      - db
    networks:
      - wallet-network

  prometheus:
    image: prom/prometheus
    container_name: wallet_prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wallet-network

  grafana:
    image: grafana/grafana
    container_name: wallet_grafana
    restart: always
    ports:
      - '3001:3000' 
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD} 
    depends_on:
      - prometheus
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  db_data: